trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DockerCompose@0
  displayName: 'Run docker compose yaml'
  inputs:
    action: Run services
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: sridockerregistry
    dockerComposeFile: docker-compose.ci.build.yaml

