version: '2.2'
services:
  hub:
    image: srikala/repo1:selenium1
    command: java -jar "C:\selenium\selenium-server-standalone-3.141.59.jar" -role hub
    ports:
      - "4444:4444"
  node:
    image: srikala/repo1:selenium1
    command: java -jar "C:\selenium\selenium-server-standalone-3.141.59.jar" -role node -hub http://hub:4444/grid/register
    ports:
      - "5555:5555"
    depends_on:
      - hub
    environment:
      HUB_HOST: hub